#!/usr/bin/env python3
"""
Agile Business -- Universal Launcher
=====================================
Single-file utility: auto-detects environment, starts the site, opens browser.

Works on: Windows, macOS, Linux
Strategies (in priority order):
  1. Docker Compose  (docker + docker-compose available)
  2. Local Dev Mode  (Node.js + Python available)

Usage:
  python start.py            # auto-detect best strategy
  python start.py --docker   # force Docker mode
  python start.py --local    # force local dev mode
  python start.py --stop     # stop running containers/processes
"""

import os
import re
import sys
import time
import shutil
import secrets
import signal
import subprocess
import webbrowser
import platform
import socket
import argparse
import textwrap

# ── Constants ──────────────────────────────────────────────────

ROOT = os.path.dirname(os.path.abspath(__file__))
SERVER_DIR = os.path.join(ROOT, "server")
CLIENT_DIR = os.path.join(ROOT, "client-new")

IS_WIN = platform.system() == "Windows"
IS_MAC = platform.system() == "Darwin"
SUPPORTED_PYTHON_MINORS = (11, 12, 13)

DOCKER_URL = "http://localhost:3000"
DEV_URL = "http://localhost:5173"

# ── Helpers ────────────────────────────────────────────────────

_children = []

def log(msg, color="cyan"):
    colors = {
        "cyan": "\033[96m", "green": "\033[92m", "yellow": "\033[93m",
        "red": "\033[91m", "bold": "\033[1m", "reset": "\033[0m",
    }
    c = colors.get(color, "")
    r = colors["reset"]
    print(f"{c}{msg}{r}")


def log_step(n, msg):
    log(f"\n>> [{n}] {msg}", "green")


def cmd_exists(name):
    return shutil.which(name) is not None


def run(cmd, cwd=None, check=True, capture=False):
    kwargs = dict(cwd=cwd or ROOT, shell=True)
    if capture:
        kwargs["stdout"] = subprocess.PIPE
        kwargs["stderr"] = subprocess.PIPE
        kwargs["text"] = True
    result = subprocess.run(cmd, **kwargs)
    if check and result.returncode != 0:
        log(f"Command failed: {cmd}", "red")
        sys.exit(1)
    return result


def run_bg(cmd, cwd=None):
    kwargs = dict(cwd=cwd or ROOT, shell=True)
    if IS_WIN:
        kwargs["creationflags"] = subprocess.CREATE_NEW_PROCESS_GROUP
    p = subprocess.Popen(cmd, **kwargs)
    _children.append(p)
    return p


def port_open(port, host="127.0.0.1", timeout=2):
    try:
        with socket.create_connection((host, port), timeout=timeout):
            return True
    except (OSError, ConnectionRefusedError):
        return False


def wait_for_port(port, label, max_wait=120):
    log(f"   Waiting for {label} on port {port}...", "yellow")
    start = time.time()
    while time.time() - start < max_wait:
        if port_open(port):
            log(f"   {label} ready!", "green")
            return True
        time.sleep(2)
    log(f"   Timeout waiting for {label} (port {port})", "red")
    return False


def open_browser(url):
    log(f"\n   Opening browser: {url}", "bold")
    time.sleep(1)
    webbrowser.open(url)


def cleanup_handler(signum, frame):
    log("\nShutting down...", "yellow")
    for p in _children:
        try:
            p.terminate()
        except Exception:
            pass
    sys.exit(0)


signal.signal(signal.SIGINT, cleanup_handler)
signal.signal(signal.SIGTERM, cleanup_handler)
if IS_WIN:
    try:
        signal.signal(signal.SIGBREAK, cleanup_handler)
    except (AttributeError, ValueError):
        pass

# ── .env Generation ────────────────────────────────────────────

DOCKER_ENV_TEMPLATE = textwrap.dedent("""\
    # Auto-generated by start.py
    DEBUG=false
    SECRET_KEY={secret}
    DOMAIN=localhost

    DB_PASSWORD=agile_local_pass
    REDIS_PASSWORD=agile_redis_pass

    MINIO_USER=minioadmin
    MINIO_PASSWORD=minioadmin123

    ELASTIC_PASSWORD=changeme

    CORS_ORIGINS=["http://localhost:3000","http://localhost:5173"]
    ADMIN_SEED_EMAIL=admin@agile.local
    ADMIN_SEED_PASSWORD=admin123
    WORKERS=2
    FRONTEND_PORT=3000
""")

SERVER_ENV_TEMPLATE = textwrap.dedent("""\
    # Auto-generated by start.py
    DEBUG=true
    SECRET_KEY={secret}
    DOMAIN=localhost
    DATABASE_URL=postgresql+asyncpg://agile:agile_pass@localhost:5432/agile_db
    REDIS_URL=redis://localhost:6379/0
    S3_ENDPOINT=http://localhost:9000
    S3_ACCESS_KEY=minioadmin
    S3_SECRET_KEY=minioadmin
    S3_BUCKET=agile-files
    ADMIN_SEED_EMAIL=admin@agile.local
    ADMIN_SEED_PASSWORD=admin123
    CORS_ORIGINS=["http://localhost:5173","http://localhost:5174","http://localhost:3000"]
    ELASTICSEARCH_URL=
""")


def ensure_env_docker():
    env_path = os.path.join(ROOT, ".env")
    if os.path.exists(env_path):
        log("   .env already exists -- using it", "green")
        return
    secret = secrets.token_urlsafe(48)
    content = DOCKER_ENV_TEMPLATE.format(secret=secret)
    with open(env_path, "w", encoding="utf-8") as f:
        f.write(content)
    log("   Created .env with safe local defaults", "green")


def ensure_env_local():
    env_path = os.path.join(SERVER_DIR, ".env")
    if os.path.exists(env_path):
        log("   server/.env already exists -- using it", "green")
        return
    secret = secrets.token_urlsafe(48)
    content = SERVER_ENV_TEMPLATE.format(secret=secret)
    with open(env_path, "w", encoding="utf-8") as f:
        f.write(content)
    log("   Created server/.env with safe local defaults", "green")


# ── Strategy: Docker Compose ──────────────────────────────────

def can_docker():
    if not cmd_exists("docker"):
        return False
    r = subprocess.run("docker info", shell=True, capture_output=True, text=True)
    return r.returncode == 0


def docker_compose_cmd():
    r = subprocess.run("docker compose version", shell=True, capture_output=True, text=True)
    if r.returncode == 0:
        return "docker compose"
    if cmd_exists("docker-compose"):
        return "docker-compose"
    return None


def start_docker():
    log("\n========================================", "cyan")
    log("  Agile Business -- Docker Launch", "cyan")
    log("========================================", "cyan")

    dc = docker_compose_cmd()
    if not dc:
        log("docker compose not found!", "red")
        sys.exit(1)

    log_step(1, "Ensuring .env configuration")
    ensure_env_docker()

    log_step(2, "Building and starting containers")
    run(f"{dc} up -d --build --remove-orphans")

    log_step(3, "Waiting for services")
    ok = wait_for_port(3000, "Frontend")
    if not ok:
        log("Frontend did not start. Check: docker compose logs frontend", "red")
        sys.exit(1)

    log_step(4, "All services running!")
    log(f"""
   Frontend:  {DOCKER_URL}
   API docs:  http://localhost:8000/docs  (via container network)
   Admin:     admin@agile.local / admin123
    """, "bold")

    open_browser(DOCKER_URL)
    log("\nSite is running. Press Ctrl+C or run 'python start.py --stop' to stop.", "green")

    try:
        while True:
            time.sleep(5)
    except KeyboardInterrupt:
        stop_docker()


def stop_docker():
    dc = docker_compose_cmd()
    if dc:
        log("Stopping containers...", "yellow")
        run(f"{dc} down", check=False)
    log("Stopped.", "green")


# ── Strategy: Local Dev  ──────────────────────────────────────

def shell_exe(cmd):
    return f'"{cmd}"' if os.path.isfile(cmd) else cmd


def get_python_version(cmd):
    r = subprocess.run(f"{shell_exe(cmd)} --version", shell=True, capture_output=True, text=True)
    if r.returncode != 0:
        return None
    text = (r.stdout + r.stderr).strip()
    m = re.search(r"Python\s+(\d+)\.(\d+)\.(\d+)", text)
    if not m:
        return None
    return tuple(int(x) for x in m.groups())


def is_supported_python(version):
    return bool(version and version[0] == 3 and version[1] in SUPPORTED_PYTHON_MINORS)


def find_python():
    """Find a supported Python 3.11-3.13 executable for this project."""
    venv_candidates = [
        os.path.join(ROOT, ".venv", "Scripts" if IS_WIN else "bin", "python.exe" if IS_WIN else "python"),
        os.path.join(ROOT, ".venv-1", "Scripts" if IS_WIN else "bin", "python.exe" if IS_WIN else "python"),
        os.path.join(SERVER_DIR, ".venv", "Scripts" if IS_WIN else "bin", "python.exe" if IS_WIN else "python"),
    ]
    for candidate in venv_candidates:
        if os.path.isfile(candidate) and is_supported_python(get_python_version(candidate)):
            return candidate

    commands = []
    if IS_WIN:
        commands.extend(["py -3.11", "py -3.12", "py -3.13"])
    commands.extend(["python3.11", "python3.12", "python3.13", "python3", "python"])

    for cmd in commands:
        if " " not in cmd and not cmd_exists(cmd):
            continue
        version = get_python_version(cmd)
        if is_supported_python(version):
            return cmd
    return None


def ensure_venv():
    venv_dir = os.path.join(ROOT, ".venv")
    venv_py = os.path.join(venv_dir, "Scripts" if IS_WIN else "bin",
                           "python.exe" if IS_WIN else "python")
    if os.path.isfile(venv_py):
        version = get_python_version(venv_py)
        if is_supported_python(version):
            log(f"   .venv exists and uses Python {version[0]}.{version[1]}.{version[2]}", "green")
            return venv_py
        log("   Existing .venv uses unsupported Python version -- recreating it", "yellow")
        shutil.rmtree(venv_dir, ignore_errors=True)

    log("   Creating Python virtual environment...", "yellow")
    py = find_python()
    if not py:
        log("Supported Python not found. Please install Python 3.11, 3.12, or 3.13.", "red")
        sys.exit(1)
    version = get_python_version(py)
    if version:
        log(f"   Using Python {version[0]}.{version[1]}.{version[2]} for the project", "green")
    run(f'{shell_exe(py)} -m venv .venv')
    return venv_py


def start_local():
    log("\n========================================", "cyan")
    log("  Agile Business -- Local Dev Launch", "cyan")
    log("========================================", "cyan")

    # Step 1: Check node
    log_step(1, "Checking Node.js")
    if not cmd_exists("node"):
        log("Node.js not found! Install from https://nodejs.org/", "red")
        sys.exit(1)
    r = run("node --version", capture=True)
    log(f"   Node.js {r.stdout.strip()}", "green")

    # Step 2: Check Python
    log_step(2, "Checking Python")
    py = find_python()
    if not py:
        log("Supported Python not found! Install Python 3.11, 3.12, or 3.13 from https://python.org/downloads/", "red")
        sys.exit(1)
    version = get_python_version(py)
    if version:
        log(f"   Compatible Python detected: {version[0]}.{version[1]}.{version[2]}", "green")

    # Step 3: Ensure .env
    log_step(3, "Ensuring server/.env configuration")
    ensure_env_local()

    # Step 4: Python venv + deps
    log_step(4, "Setting up Python environment")
    venv_py = ensure_venv()
    log("   Installing Python dependencies (progress will be shown below)...", "yellow")
    run(f'{shell_exe(venv_py)} -m pip install --upgrade pip', check=False)
    run(f'{shell_exe(venv_py)} -m pip install --prefer-binary -r server/requirements.txt')
    log("   Python dependencies ready", "green")

    # Step 5: npm install
    log_step(5, "Installing frontend dependencies")
    if not os.path.isdir(os.path.join(CLIENT_DIR, "node_modules")):
        run("npm install", cwd=CLIENT_DIR)
    else:
        log("   node_modules exists -- skipping npm install", "green")

    # Install root concurrently if missing
    if not os.path.isdir(os.path.join(ROOT, "node_modules")):
        run("npm install", cwd=ROOT)

    # Step 6: DB migrations (best effort)
    log_step(6, "Running database migrations (best effort)")
    r = subprocess.run(
        f'"{venv_py}" -m alembic upgrade head',
        shell=True, cwd=SERVER_DIR,
        capture_output=True, text=True
    )
    if r.returncode == 0:
        log("   Migrations applied", "green")
    else:
        log("   Migrations skipped (DB may not be ready or already up-to-date)", "yellow")

    # Step 7: Start backend + frontend
    log_step(7, "Starting backend and frontend")

    uvicorn_cmd = f'"{venv_py}" -m uvicorn app.main:app --host 127.0.0.1 --port 8000'
    backend_proc = run_bg(uvicorn_cmd, cwd=SERVER_DIR)

    vite_cmd = "npx vite --host"
    frontend_proc = run_bg(vite_cmd, cwd=CLIENT_DIR)

    # Step 8: Wait and open
    log_step(8, "Waiting for services to start")
    api_ok = wait_for_port(8000, "Backend API", max_wait=60)
    ui_ok = wait_for_port(5173, "Frontend (Vite)", max_wait=60)

    if not api_ok:
        log("Backend did not start. Check server/.env and PostgreSQL.", "red")
    if not ui_ok:
        log("Frontend did not start. Check node_modules.", "red")

    if api_ok and ui_ok:
        log(f"""
   Frontend:  {DEV_URL}
   API docs:  http://localhost:8000/docs
   Admin:     admin@agile.local / admin123
        """, "bold")
        open_browser(DEV_URL)
    elif ui_ok:
        open_browser(DEV_URL)

    log("\nSite is running. Press Ctrl+C to stop.", "green")

    try:
        backend_proc.wait()
    except KeyboardInterrupt:
        cleanup_handler(None, None)


# ── Main ──────────────────────────────────────────────────────

def print_banner():
    log("""
  ___        _ _        ____            _
 / _ \\      (_) |      |  _ \\          (_)
/ /_\\ \\ __ _ _| | ___  | |_) |_   _ ___ _ _ __   ___  ___ ___
|  _  |/ _` | | |/ _ \\ |  _ <| | | / __| | '_ \\ / _ \\/ __/ __|
| | | | (_| | | |  __/ | |_) | |_| \\__ \\ | | | |  __/\\__ \\__ \\
\\_| |_/\\__, |_|_|\\___| |____/ \\__,_|___/_|_| |_|\\___||___/___/
        __/ |
       |___/       Universal Launcher v1.0
    """, "cyan")


def main():
    parser = argparse.ArgumentParser(description="Agile Business -- Universal Launcher")
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--docker", action="store_true", help="Force Docker Compose mode")
    group.add_argument("--local", action="store_true", help="Force local dev mode (Node + Python)")
    group.add_argument("--stop", action="store_true", help="Stop running Docker containers")
    args = parser.parse_args()

    print_banner()

    if args.stop:
        stop_docker()
        return

    if args.docker:
        if not can_docker():
            log("Docker is not running or not installed!", "red")
            log("Install Docker Desktop: https://www.docker.com/products/docker-desktop/", "yellow")
            sys.exit(1)
        start_docker()
        return

    if args.local:
        start_local()
        return

    # Auto-detect
    log("Auto-detecting best launch strategy...\n", "bold")

    has_docker = can_docker()
    has_dc = docker_compose_cmd() is not None
    has_node = cmd_exists("node")
    has_python = find_python() is not None

    log(f"   Docker:         {'YES' if has_docker else 'NO'}", "green" if has_docker else "yellow")
    log(f"   Docker Compose: {'YES' if has_dc else 'NO'}", "green" if has_dc else "yellow")
    log(f"   Node.js:        {'YES' if has_node else 'NO'}", "green" if has_node else "yellow")
    log(f"   Python 3:       {'YES' if has_python else 'NO'}", "green" if has_python else "yellow")

    if has_docker and has_dc:
        log("\n   -> Using Docker Compose (recommended)", "bold")
        start_docker()
    elif has_node and has_python:
        log("\n   -> Using Local Dev Mode (Node.js + Python)", "bold")
        start_local()
    else:
        log("\nCannot start! Need either:", "red")
        log("  a) Docker Desktop  -- https://www.docker.com/products/docker-desktop/", "yellow")
        log("  b) Node.js + Python -- https://nodejs.org/ + https://python.org/", "yellow")
        sys.exit(1)


if __name__ == "__main__":
    main()
